### ISSUE TITLE
The whole plugin is broken

### ISSUE THREAD

**Issue by J1b1x** [ColinHDev/CPlot#10]
Yo,
First thing: You changed the return type of the extecute function to \Generator, but didn't changed the return type of the subcomands too, so it causes an error

Second thing: 90% of the function that you call (for example getProvider(), getWorld() (in the DataProvider), Plot::fromPosition and many more) doesn't exist, so actually no command is usable

**Comment by ColinHDev** [comment]
I know, I am currently in midst of rewriting the plugin to use [libasynql](https://github.com/poggit/libasynql) and [await-generator](https://github.com/SOF3/await-generator). But since this is a complex task, I didn't finish it in one go.
Yesterday I updated all the event listeners (https://github.com/ColinHDev/CPlot/commit/3fd12b59b0b3c825fd7ab2de021cfb943eff4015) and started working on the commands. That's why it gives you those errors.

**Comment by J1b1x** [comment]
> I know, I am currently in midst of rewriting the plugin to use [libasynql](https://github.com/poggit/libasynql) and [await-generator](https://github.com/SOF3/await-generator). But since this is a complex task, I didn't finish it in one go. Yesterday I updated all the event listeners ([3fd12b5](https://github.com/ColinHDev/CPlot/commit/3fd12b59b0b3c825fd7ab2de021cfb943eff4015)) and started working on the commands. That's why it gives you those errors.

Alright, good luck ^^

**Comment by ColinHDev** [comment]
Everything should be updated now, therefore I will close this issue.
If there are any errors I made during updating, please create a new issue.
