### ISSUE TITLE
Issue with PlayerEnterPlotEvent 

### ISSUE THREAD

**Issue by TM-Grant4** [ColinHDev/CPlot#109]
`/plot visit`
`/plot home`
(aliases too)

When using any of the commands above it doesnt fire the PlayerEnterPlotEvent, and i need that for my system I'm doing. 

If this is how it was intended to be could someone help me with PlayerEnteredPlotEvent, and how it works

**Comment by supercrafter333** [comment]
Should be fixed in #111

**Comment by TM-Grant4** [comment]
> Should be fixed in #111

Ok thank you!

**Comment by ColinHDev** [comment]
> When using any of the commands above it doesnt fire the PlayerEnterPlotEvent, and i need that for my system I'm doing.
The plugin uses an asynchronous way of fetching the data of a plot. This way, if a player walks into a plot, the data might not be loaded and still take some time to do so.
`PlayerEnterPlotEvent` is then only called, if the data of the plot is already loaded. But since it might not be the case, there is no guarantee.
`PlayerEnteredPlotEvent` is always called, but does not allow you to cancel it, since the player entered the plot in the past.

It's a scuffed system, but I didn't come up with anything better back then.
