### ISSUE TITLE
[API]: Skip PM4 and program CPlot for PM5

### ISSUE THREAD

**Issue by supercrafter333** [ColinHDev/CPlot#25]
In december this year, PocketMine-MP will release PocketMine-MP v5.0.0.
I don't think that CPlot will be completed soon. But if you skip PM4 and program CPlot directly in PM5, CPlot can be finished with PM5.
You also don't have to update soooo much.

It's just a idea. ^^

**Comment by ColinHDev** [comment]
Dylan already said that PM5 won't change as much as PM4 did, especially since PM5 will be in development for only one year, PM4 for (I believe) over three. If I remember correctly, the current `next-major` branch doesn't even have that many bc breaks, since Dylan mostly works on the `modern-world-support` branch.
Also, I am not only developing this plugin for everyone but also for a server I am employed at. So there is no reason for me to stopping to support PM4 at this repo if I would have to continue it at https://github.com/EntenGamesDE/CPlot.

**Comment by supercrafter333** [comment]
Okay, fine.... But EntenGames closed. Or doesn't it?

**Comment by ColinHDev** [comment]
The server closed, but the company keeps the name and therefore the GitHub organization
