### ISSUE TITLE
Suggest

### ISSUE THREAD

**Issue by ghost** [ColinHDev/CPlot#49]
as well as the systems to change the edge and also the plot wall, I think a new system would be good to change the top floor of the plot by some block in a ui

**Comment by ColinHDev** [comment]
So a command that would replace the grass layer of the plot? Or what do you mean by `top floor`

**Comment by ghost** [comment]
Yes, it would be the first grass pad of the plot, just like the wall systems, only specifically for that, it would be an even better feature for the plugin in my opinion

**Comment by ColinHDev** [comment]
Nope sorry. The idea for those commands was not to make it easier to build your plot but to give users the ability to customize blocks that they could not change otherwise. (Players are not able to change their plot's border or wall without an admin.)
The grass layer of the plot can be changed by players and therefore does not require an additional command for that.
