### ISSUE TITLE
Commands need to be called twice or take minutes to respond

### ISSUE THREAD

**Issue by Jerbyyy0** [ColinHDev/CPlot#66]
If i do /p reset its need 10 minutes for reset.
Every command i have to execute it twice.
I used the Dev Version 131+
All versions about 131 have this bugs.
Dev version 130 is working.

https://www.mediafire.com/file/zer9e23ptnqjfpd/2022-10-17+21-36-13.mp4/file
![image](https://user-images.githubusercontent.com/59423442/199627107-20a555a2-d7b4-4640-8e70-d5cedb837f9a.png)

**Comment by ColinHDev** [comment]
Reproduced on a clean server (`colinh.dev`:`19133`)

**Comment by ColinHDev** [comment]
Probably related to https://github.com/poggit/libasynql/issues/90, as far as I remember

**Comment by ColinHDev** [comment]
This is fixed for now by downgrading our version of libasynql since there seems to be no movement on https://github.com/poggit/libasynql/issues/90.
Although this might make this plugin incompatible with php8.1, since https://github.com/poggit/libasynql/issues/87 was only fixed after the broken changes were made that cause https://github.com/poggit/libasynql/issues/90.
