### ISSUE TITLE
[Crash]: Crash on PlayerMove event

### ISSUE THREAD

**Issue by Bubbelwubbel** [ColinHDev/CPlot#7]
![image](https://user-images.githubusercontent.com/65186341/150203982-64abb4f8-9de4-4811-95e9-9bfc4ceb8598.png)

**Comment by ColinHDev** [comment]
Please don't send images of the error screens or the files, they are a pain to read, especially when I'm on mobile.

This bug exists since the repo is currently in midst of getting a database rewrite. Some classes are already rewritten and should work, while others still use the old which no longer exists.
I need some time, to fix all of them, but I am currently in the exam phase, so I do have not much time to code. (And even if I have time, I don't have time to test that much.)

**Comment by ColinHDev** [comment]
But once I am finished, I will add a `main` branch to the repo, where the code should work. This way, you can use the plugin from that branch, while I have my fun in `development`

**Comment by Bubbelwubbel** [comment]
ok 👌

**Comment by ColinHDev** [comment]
Everything should be updated now, therefore I will close this issue.
If there are any errors I made during updating, please create a new issue.
