### ISSUE TITLE
Chestshop do not work in CPlot

### ISSUE THREAD

**Issue by BananaGER** [ColinHDev/CPlot#74]
Hey,

I installed the Chestshop Plugin but i noticed, that if you want to buy something on a Plot, you cant do it only if you have operator permissions is ther a flag that you can set or something?

**Comment by supercrafter333** [comment]
The chestshop plugin was developed for MyPlot. Ask the developer of ChestShop to program it for CPlot.

**Comment by ColinHDev** [comment]
> Hey,
> 
> I installed the Chestshop Plugin but i noticed, that if you want to buy something on a Plot, you cant do it only if you have operator permissions is ther a flag that you can set or something?

The `PlayerInteractEvent` is cancelled if a player has no permission to interact with a certain block, like a sign or a chest. If that plugin relies on that particular event to be not cancelled, then it won't work on plots. You could add signs (if that plugin uses signs for the transaction) to the plot's `use` flag but by that, everyone can interact and possibly colour your sign.
In my opinion, you should create an issue on that plugin's GitHub page, since if it doesn't work with CPlot, then it most likely won't with other world protection plugins, where you might have a shop in your protected server spawn.
