### ISSUE TITLE
MyPlot Support

### ISSUE THREAD

**Issue by xxAROX** [ColinHDev/CPlot#9]
convert myplot config to your database format, for switching from myplot plugin to this

**Comment by supercrafter333** [comment]
I think this is a thing for an extra plugin. It should not be implemented in CPlot directly.

**Comment by ColinHDev** [comment]
I always planned to support MyPlot worlds with a proper conversion plugin. But I never was sure, whether that should be part of CPlot itself or of an extra plugin.
Making this database and config compatible with the ones from MyPlot is not just limiting due to MyPlot's database design, but also useless, since I would still need a conversion for the worlds to change the generators. Also, this plugin is far too deep in the development that it would make sense to rewrite nearly everything so that MyPlot can be supported on the fly.
While MyPlot support is on my TODO list, it has no big priority, since there are many things that need to be addressed.
- [ ] Database conversion (includes world data and plot data that we need to make compatible, but also issues like that MyPlot uses player names, while CPlot UUIDs)
- [ ] World and generator conversion (position x=0, z=0 is on a plot in MyPlot, but on the road in CPlot - our worlds are offset by the size of the road, so to support MyPlot, we would need to support two different world types, which would result in having two different calculations)

**Comment by ColinHDev** [comment]
Updates will be pushed to https://github.com/ColinHDev/CPlot/tree/myplot-support.
But don't expect too many updates for now.

**Comment by jasonw4331** [comment]
Update to this issue: 
- [x] World generator conversion is done in PR #17
- [ ] Database conversion is work in progress

**Comment by ColinHDev** [comment]
This got implemented in #17 for CPlot's PM5 branch.
